FROM php:8.2-fpm-buster

COPY .docker/php/php.ini /usr/local/etc/php/conf.d/docker-php-config.ini
COPY .docker/php/php.ini /usr/local/etc/php/php.ini

WORKDIR /var/www/symfony

RUN apt-get update && apt-get install -y \
    gnupg \
    g++ \
    procps \
    openssl \
    git \
    unzip \
    zlib1g-dev \
    libzip-dev \
    libfreetype6-dev \
    libpng-dev \
    libjpeg-dev \
    libicu-dev  \
    libonig-dev \
    libxslt1-dev \
    libpq-dev \
    acl \
    && echo 'alias sf="php bin/console"' >> ~/.bashrc

RUN docker-php-ext-install intl
RUN docker-php-ext-install opcache

RUN curl -sS https://get.symfony.com/cli/installer | bash \
    && mv /root/.symfony5/bin/symfony /usr/local/bin/symfony
    
ENV COMPOSER_ALLOW_SUPERUSER=1

RUN docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pdo pdo_pgsql pgsql \
    && docker-php-ext-configure gd --with-jpeg --with-freetype 

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY ./ ./

# Fix permissions
RUN chown -R www-data:www-data /var/www/symfony && chmod +x bin/console

RUN git config --global --add safe.directory /var/www/symfony

# Now install dependencies
RUN composer install --optimize-autoloader

# Dump autoloader
RUN composer dump-autoload --optimize